[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
exclude = ["programs/openbook_v2", "programs/switchboard-on-demand"]

[scripts]
test = "echo"
lint = "yarn prettify:fix && cargo fmt"
build = "anchor build"
deploy = "anchor deploy"

[programs.localnet]
apex = "11111111111111111111111111111111"
pyth = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"

[programs.devnet]
apex = "11111111111111111111111111111111"
pyth = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"

[programs.mainnet]
apex = "11111111111111111111111111111111"
pyth = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./deps/configs/usdc.json"

[[test.validator.account]]
address = "3rdJbqfnagQ4yx9HXJViD4zc4xpiSqmFsKpPuSCQVyQL"
filename = "./deps/configs/pyth_lazer_storage.json"